baseURL = "https://localhost:1313"
title = "東京大学海洋ロボット研究会"
author = "東京大学海洋ロボット研究会"
languageCode = "jp"
DefaultContentLanguage = "jp"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  showBlog = true
  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo/logo.svg"
    alt = "UT Marine"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "東京大学海洋ロボット研究会"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "A Hugo Theme for OSSProject, Companies, Organization..."
    meta_og_title = "Tella"
    meta_og_type = "website"
    meta_og_url = "https://tella.pages.dev"
    meta_og_image = "https://raw.githubusercontent.com/opera7133/tella/master/images/tn.png"
    meta_og_description = "A Hugo Theme for OSSProject, Companies, Organization..."
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@username"
    meta_twitter_creator = "@username"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About us"
    url = "/about/"
    weight = 1
  
  [[menu.main]]
    identifier = "project"
    name = "Project"
    url = "/project/"
    weight = 2
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 3

  [[menu.main]]
    identifier = "recruitment"
    name = "Recruitment"
    url = "/recruitment/"
    weight = 4

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 5

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/UTokyo-Marine-Robotics-Team"
    pre = "<i class='icon-github text-2xl'></i>"
      weight = 2
